# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: JPackage MacOS

on:
  workflow_dispatch
#  push:
#    branches: [ $default-branch ]
#  pull_request:
#    branches: [ $default-branch ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Build jar file with Ant
      run: ant -noinput -buildfile timer/build.xml
    - name: jpackage
      run: >
        jpackage
        --type pkg
        --name derby-timer
        --verbose 
        --input timer/dist/lib
        --main-jar derby-timer.jar
        --main-class org.jeffpiazza.derby.TimerMain
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: dist-without-markdown
        path: derby-timer*.pkg
